### ISSUE TITLE
Task 1. Storm Typing

### ISSUE THREAD

**Issue by sebastienlanglois** [hydrologie/sefm#2]
# Task 1 - Storm Typing
Storm typing classifies storms events into classes that are nearly homogeneous with respects to their generating phenomenon. This allows to evaluate more homogeunous distributions for each storm type when computing precipitation-frequency analysis rather than a traditionel mixed distribution with all the storms. Homogeneity is an assumption when computing frequency analysis which makes storm typing all the more important.

# Task 1 - Decision Log 
- Project Area
  - [ ] Expand project area for storm typing to include one additional column on the east and west sides, two rows to the south and one row to the north

       - This larger project area will facilitate storm transposition to the watershed.
  - The focus will be on this project area only to develop the initial automated algorithm which can then be tested and refined if necessary for other areas in subsequent projects.

- Reanalysis Data and Storm Typing Zones
  - 20th Century Reanalysis Data Version 3 with a resolution of 1 degree by 1 degree will be used for the storm typing zones. The computation of gradients in pressure heights assigned to a cell will encompass a larger area; however, it is suitable to assess CAPE and precipitation rate per 1x1 degree cell.
  - The 1x1 grid will be used throughout the Province and numbered accordingly to maintain the number sequencing with a subset selected for analysis.
  - References will be consulted for validation of the 20th Century Reanalysis data.
  - The maximum 3-hour value over the storm key duration (i.e., 72-hours or 3-days) will be used as the grid cell value for a given day for a given parameter.
- Manual Storm Typing
  - [ ]  About 50 storms will be initially manually typed by Hydro Quebec.
  - [ ]  Hydro Quebec will provide a shapefile of the project area and for which DTN will then provide a list of storms from their Extreme Storm Database.
  - [ ]  Other storms will be selected by Hydro Quebec from other reports (e.g., PMP study) and from their previous work identifying a variety of storms with different characteristics (e.g., large magnitudes, common storms, large spatial extents)
  - [ ]  After an initial effort of manual storm typing by Hydro Quebec, we will meet to review results and discuss questionable cases – by the third week of January (Sebastian will set this up); with a goal to complete storm typing by end of February.
